### ISSUE TITLE
Style question - 3 spaces indent?

### ISSUE THREAD

**Issue by jcrben** [mrbaseman/parse_yaml#17]
I noticed that the whole parse_yaml file uses 3 spaces to indent. Is this a deliberate style choice? It seems unusual. Why not 4?

I ran in it thru https://github.com/lovesegfault/beautysh which set it to 4 spaces indentation as its default.

**Comment by mrbaseman** [comment]
ehm, no. It's not a deliberate style choice, and it's not consistently 3 spaces. In some places it's actually 4.
I try to avoid tab characters, but I wouldn't even guarantee that there are none, because in one place or another, my editor might have decided to replace 8 spaces by one tab :-)
well, recently, I haven't found the time to go through the issues and pull requests here, but I'll keep this one in mind and beautify the code once the proposed changes are merged. 
BTW looking at the code quite some time after I have done this quick hack, I guess I should decorate it a bit at least with a few comments

**Comment by mrbaseman** [comment]
One of the PR has brought already some explaining comments. I have then fixed indentation in [this commit](https://github.com/mrbaseman/parse_yaml/commit/8fc1ad67a0a72eb2d9717f035ea1cff680a310b5), so I think this one is addressed now and can be closed. If you disagree, please feel free to reopen with a comment.
